### ISSUE TITLE
How Far can 100 Samples Go? Unlocking Zero-Shot Translation with Tiny Multi-Parallel Data

### ISSUE THREAD

**Issue by alvations** [moore3930/MultiParallelFinetuning4MMT#1]
Interesting work on mini dataset! Look forward for the model, data subset and eval code!

**Comment by moore3930** [comment]
Sure, we are on the way back from ACL and will release them in days. Thanks for your interest.

**Comment by moore3930** [comment]
Hi, @alvations, thanks again for your interest, and sorry for the delay. The code, model, and datasets are released. Please feel free to let us know if you see any issues. Cheers

**Comment by moore3930** [comment]
Completed
